export const COURSE_LEVEL_MAP: Record<string, string[]> = {
    LX: ['LX A', 'LX B', 'LX C', 'LX D', 'LX E', 'LX F'],
    GT: ['GTi', 'GT1', 'GT2', 'GT3', 'GT4'],
    MGT: ['MGT1', 'MGT2', 'MGT3', 'MGT4'],
    S: ['S1', 'S2', 'S3', 'S4'],
    R: ['R1', 'R2', 'R3', 'R4'],
    MAG: ['MAG1', 'MAG1+', 'MAG2', 'MAG2+', 'MAG3', 'MAG4']
  };
  
  export const COURSES = Object.keys(COURSE_LEVEL_MAP);
  
  export const CAMPUS_LIST = [
    '폴리어학원(강동)',
    '폴리어학원(강서)',
    '폴리어학원(관악)',
    '폴리어학원(광교)',
    '폴리어학원(광명)',
    '폴리어학원(광산)',
    '폴리어학원(광안)',
    '폴리어학원(광주봉선)',
    '폴리어학원(광진)',
    '폴리어학원(구리/남양주)',
    '폴리어학원(구미)',
    '폴리어학원(김포)',
    '폴리어학원(김해)',
    '폴리어학원(남동)',
    '폴리어학원(달서)',
    '폴리어학원(대구북구)',
    '폴리어학원(대전)',
    '폴리어학원(대치폴리매그넷)',
    '폴리어학원(덕양)',
    '폴리어학원(동대문)',
    '폴리어학원(동래)',
    '폴리어학원(동탄)',
    '폴리어학원(마산)',
    '폴리어학원(마포)',
    '폴리어학원(목동)',
    '폴리어학원(부산명지)',
    '폴리어학원(부산화명)',
    '폴리어학원(부천)',
    '폴리어학원(분당)',
    '폴리어학원(서수원)',
    '폴리어학원(성동)',
    '폴리어학원(성북)',
    '폴리어학원(세종)',
    '폴리어학원(송도)',
    '폴리어학원(송파)',
    '폴리어학원(수성)',
    '폴리어학원(수지별관)',
    '폴리어학원(수지본관)',
    '폴리어학원(시흥장현)',
    '폴리어학원(영통)',
    '폴리어학원(운정)',
    '폴리어학원(울산남구)',
    '폴리어학원(원주)',
    '폴리어학원(위례)',
    '폴리어학원(유성)',
    '폴리어학원(은평)',
    '폴리어학원(일산)',
    '폴리어학원(전주)',
    '폴리어학원(정발)',
    '폴리어학원(중계)',
    '폴리어학원(진주)',
    '폴리어학원(창원)',
    '폴리어학원(천안)',
    '폴리어학원(청라)',
    '폴리어학원(청주)',
    '폴리어학원(평촌)',
    '폴리어학원(평택지제)',
    '폴리어학원(포항)',
    '폴리어학원(하남미사)',
    '폴리어학원(해운대)'
  ];
  
  export const CAMPUS_INFO = [
    { name: '폴리어학원(강동)', type: '분원', region: '서울권', years: 7 },
    { name: '폴리어학원(강서)', type: '분원', region: '서울권', years: 13 },
    { name: '폴리어학원(관악)', type: '분원', region: '서울권', years: 21 },
    { name: '폴리어학원(광교)', type: '직영', region: '경인권', years: 4 },
    { name: '폴리어학원(광명)', type: '직영', region: '경인권', years: 22 },
    { name: '폴리어학원(광산)', type: '분원', region: '전라권', years: 9 },
    { name: '폴리어학원(광안)', type: '분원', region: '경상권', years: 16 },
    { name: '폴리어학원(광주봉선)', type: '분원', region: '전라권', years: 1 },
    { name: '폴리어학원(광진)', type: '분원', region: '서울권', years: 11 },
    { name: '폴리어학원(구리/남양주)', type: '분원', region: '경인권', years: 17 },
    { name: '폴리어학원(구미)', type: '분원', region: '경상권', years: 15 },
    { name: '폴리어학원(김포)', type: '분원', region: '경인권', years: 15 },
    { name: '폴리어학원(김해)', type: '분원', region: '경상권', years: 9 },
    { name: '폴리어학원(남동)', type: '분원', region: '경인권', years: 9 },
    { name: '폴리어학원(달서)', type: '분원', region: '경상권', years: 17 },
    { name: '폴리어학원(대구북구)', type: '분원', region: '경상권', years: 3 },
    { name: '폴리어학원(대전)', type: '직영', region: '충청권', years: 22 },
    { name: '대치폴리매그넷', type: '직영', region: '서울권', years: 3 },
    { name: '폴리어학원(덕양)', type: '분원', region: '경인권', years: 24 },
    { name: '폴리어학원(동대문)', type: '분원', region: '서울권', years: 19 },
    { name: '폴리어학원(동래)', type: '분원', region: '경상권', years: 7 },
    { name: '폴리어학원(동탄)', type: '분원', region: '경인권', years: 18 },
    { name: '폴리어학원(마산)', type: '분원', region: '경상권', years: 7 },
    { name: '폴리어학원(마포)', type: '분원', region: '서울권', years: 19 },
    { name: '폴리어학원(목동)', type: '직영', region: '서울권', years: 24 },
    { name: '폴리어학원(부산명지)', type: '분원', region: '경상권', years: 2 },
    { name: '폴리어학원(부산화명)', type: '분원', region: '경상권', years: 2 },
    { name: '폴리어학원(부천)', type: '분원', region: '경인권', years: 24 },
    { name: '폴리어학원(분당)', type: '직영', region: '경인권', years: 19 },
    { name: '폴리어학원(서대문)', type: '분원', region: '서울권', years: 18 },
    { name: '폴리어학원(서수원)', type: null, region: null, years: null },
    { name: '폴리어학원(성동)', type: '분원', region: '서울권', years: 20 },
    { name: '폴리어학원(성북)', type: '분원', region: '서울권', years: 19 },
    { name: '폴리어학원(세종)', type: '분원', region: '충청권', years: 11 },
    { name: '폴리어학원(송도)', type: '직영', region: '경인권', years: 24 },
    { name: '폴리어학원(송파)', type: '직영', region: '서울권', years: 19 },
    { name: '폴리어학원(수성)', type: '분원', region: '경상권', years: 19 },
    { name: '폴리어학원(수지별관)', type: '직영', region: '경인권', years: 4 },
    { name: '폴리어학원(수지본관)', type: null, region: null, years: null },
    { name: '폴리어학원(시흥장현)', type: '분원', region: '경인권', years: 2 },
    { name: '폴리어학원(영통)', type: '분원', region: '경인권', years: 22 },
    { name: '폴리어학원(운정)', type: '직영', region: '경인권', years: 3 },
    { name: '폴리어학원(울산남구)', type: '분원', region: '경상권', years: 3 },
    { name: '폴리어학원(원주)', type: '분원', region: '강원권', years: 1 },
    { name: '폴리어학원(위례)', type: '직영', region: '서울권', years: 5 },
    { name: '폴리어학원(유성)', type: '직영', region: '충청권', years: 20 },
    { name: '폴리어학원(은평)', type: '분원', region: '서울권', years: 12 },
    { name: '폴리어학원(일산)', type: null, region: null, years: null },
    { name: '폴리어학원(전주)', type: '분원', region: '전라권', years: 17 },
    { name: '폴리어학원(정발)', type: '직영', region: '경인권', years: 27 },
    { name: '폴리어학원(중계)', type: '직영', region: '서울권', years: 24 },
    { name: '폴리어학원(진주)', type: '분원', region: '경상권', years: 2 },
    { name: '폴리어학원(창원)', type: '분원', region: '경상권', years: 18 },
    { name: '폴리어학원(천안)', type: '분원', region: '충청권', years: 16 },
    { name: '폴리어학원(청라)', type: '분원', region: '경인권', years: 8 },
    { name: '폴리어학원(청주)', type: '분원', region: '충청권', years: 14 },
    { name: '폴리어학원(평촌)', type: '분원', region: '경인권', years: 24 },
    { name: '폴리어학원(평택지제)', type: '분원', region: '경인권', years: 1 },
    { name: '폴리어학원(포항)', type: '분원', region: '경상권', years: 18 },
    { name: '폴리어학원(하남미사)', type: '분원', region: '경인권', years: 5 },
    { name: '폴리어학원(해운대)', type: '분원', region: '경상권', years: 9 }
  ];
  